/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProprietarioRouteImport } from './routes/proprietario'
import { Route as PendenciasRouteImport } from './routes/pendencias'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as ItensControleRouteImport } from './routes/itens-controle'
import { Route as DisciplinasRouteImport } from './routes/disciplinas'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as IndexRouteImport } from './routes/index'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioRoute = ProprietarioRouteImport.update({
  id: '/proprietario',
  path: '/proprietario',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenciasRoute = PendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const ItensControleRoute = ItensControleRouteImport.update({
  id: '/itens-controle',
  path: '/itens-controle',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplinasRoute = DisciplinasRouteImport.update({
  id: '/disciplinas',
  path: '/disciplinas',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/disciplinas': typeof DisciplinasRoute
  '/itens-controle': typeof ItensControleRoute
  '/obras': typeof ObrasRoute
  '/pendencias': typeof PendenciasRoute
  '/proprietario': typeof ProprietarioRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/disciplinas': typeof DisciplinasRoute
  '/itens-controle': typeof ItensControleRoute
  '/obras': typeof ObrasRoute
  '/pendencias': typeof PendenciasRoute
  '/proprietario': typeof ProprietarioRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/disciplinas': typeof DisciplinasRoute
  '/itens-controle': typeof ItensControleRoute
  '/obras': typeof ObrasRoute
  '/pendencias': typeof PendenciasRoute
  '/proprietario': typeof ProprietarioRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diario'
    | '/disciplinas'
    | '/itens-controle'
    | '/obras'
    | '/pendencias'
    | '/proprietario'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diario'
    | '/disciplinas'
    | '/itens-controle'
    | '/obras'
    | '/pendencias'
    | '/proprietario'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/diario'
    | '/disciplinas'
    | '/itens-controle'
    | '/obras'
    | '/pendencias'
    | '/proprietario'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiarioRoute: typeof DiarioRoute
  DisciplinasRoute: typeof DisciplinasRoute
  ItensControleRoute: typeof ItensControleRoute
  ObrasRoute: typeof ObrasRoute
  PendenciasRoute: typeof PendenciasRoute
  ProprietarioRoute: typeof ProprietarioRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario': {
      id: '/proprietario'
      path: '/proprietario'
      fullPath: '/proprietario'
      preLoaderRoute: typeof ProprietarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendencias': {
      id: '/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof PendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itens-controle': {
      id: '/itens-controle'
      path: '/itens-controle'
      fullPath: '/itens-controle'
      preLoaderRoute: typeof ItensControleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disciplinas': {
      id: '/disciplinas'
      path: '/disciplinas'
      fullPath: '/disciplinas'
      preLoaderRoute: typeof DisciplinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiarioRoute: DiarioRoute,
  DisciplinasRoute: DisciplinasRoute,
  ItensControleRoute: ItensControleRoute,
  ObrasRoute: ObrasRoute,
  PendenciasRoute: PendenciasRoute,
  ProprietarioRoute: ProprietarioRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
